[package]
name = "learning-wpu"
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
env_logger = "0.11.5"
wgpu = "24.0.1"
winit = "0.30.5"
pollster = "0.4.0"
rayon = "1.10.0"
common = { path = "common" }

[workspace]
members = [ "buffer-and-indices", "common", "initial-tutorial", "the-pipeline","the-surface"]
