[package]
name = "uniform-buffers-an-camera"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = { workspace = true }
utils = { workspace = true }
common = { workspace = true }
winit = { workspace = true }
bytemuck = { workspace = true }
pollster = { workspace = true }
image = { workspace = true }
state-derive = { workspace = true }
cgmath = "0.18.0" # used to do the math related to the camera